spring:
  application:
    name: ocr-worker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

dms:
  rmq:
    exchange: dms.exchange
    queue:
      upload: dms.upload.queue
    routing:
      upload: upload
