services:
  db:
    image: postgres:15
    container_name: dms-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dmsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dmsdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: dms-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      ELASTICSEARCH_URL: http://elasticsearch:9200

      DMS_RMQ_EXCHANGE: dms.exchange
      DMS_RMQ_ROUTING_UPLOAD: dms.document.uploaded
      DMS_RMQ_QUEUE_UPLOAD: dms.document.uploaded
      DMS_RMQ_QUEUE_INDEX: dms.document.index
      DMS_RMQ_ROUTING_INDEX: dms.document.index

      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-minio}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minio123}
      S3_BUCKET: documents
      S3_PATH_STYLE: "true"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -o /dev/null http://localhost:8080/actuator/health/readiness"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dms-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    container_name: dms-minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Admin Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ocr-worker:
    build:
      context: ./ocr-worker
      dockerfile: Dockerfile
    container_name: dms-ocr-worker
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

      DMS_RMQ_EXCHANGE: dms.exchange
      DMS_RMQ_ROUTING_UPLOAD: dms.document.uploaded
      DMS_RMQ_QUEUE_UPLOAD: dms.document.uploaded

      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-minio}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minio123}
      S3_BUCKET: documents
      S3_REGION: us-east-1
      S3_PATH_STYLE: "true"
      SPRING_PROFILES_ACTIVE: docker

      # HIER schon vorbereiten, brauchen wir später im Code:
      GENAI_WORKER_URL: http://genai-worker:8090/api/genai/summarize
      #BACKEND_BASE_URL: http://backend:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
      genai-worker:
        condition: service_started

  genai-worker:
    build:
      context: ./genai-worker
      dockerfile: Dockerfile
    container_name: genai-worker
    restart: always
    ports:
      - "8090:8090"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  indexing-worker:
    build:
      context: ./indexing-worker
      dockerfile: Dockerfile
    container_name: dms-indexing-worker
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health | grep -E '\"status\":\"(yellow|green)\"' || exit 1"
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s



volumes:
  db_data:
  minio_data:
  pg_data:
  rabbitmq_data:
