spring:
  datasource:
    url: jdbc:postgresql://db:5432/dmsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

schedule:
  input-folder: /data/incoming
  archive-folder: /data/archive
